<div class="footer">
    	<div class="copyright">
        	<p>Copyright? 2012-2022 Photowall Inc, All Rights Reserved.</p>
            <p>照片墙 版权所有 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;版本：1.0.0</p>
            <a href="http://www.tangerteq.com"><p>Powered by Tanger TEQ LLC.</p></a>
        </div>
        <div class="clearfix"></div>
    </div>
</div>

<!--Effect script-->
<script>
        $('.link').tooltip();
</script>
</body>
</html>